### ISSUE TITLE
a single ISO-8859-1 character seems to get lost 

### ISSUE THREAD

**Issue by desaster** [desaster/epic5-bugs#2]
Commit ID: `e76e9a1447338c97ae0efa22210e66812f627d9d`
info(i) == 1827
## Example 1

[tcpdump of example 1 (.txt)](../blob/master/single-charater-goes-missing/epic5encoding1.txt?raw=1)

![Screenshot1](../blob/master/single-charater-goes-missing/epic5encoding1.png?raw=1)
## Example 2

![Screenshot1](../blob/master/single-charater-goes-missing/epic5encoding2.png?raw=1)

**Comment by derekschrock** [comment]
![screen shot 2015-08-16 at 2 04 28 pm](https://cloud.githubusercontent.com/assets/1100398/9294586/e7136258-441f-11e5-8f9c-651c642df7f2.JPG)

**Comment by desaster** [comment]
fixed in 1829
